name: Documentation GH-Pages Action
description: Generate the code, asyncapi and openapi documentation and push it on Github Pages.

inputs:

  should-generate-code-documentation:
    description: 'True if you want to generate the code documentation, false otherwise.'
    default: 'false'
    required: false
    
  code-documentation-generation-command:
    description: 'The command to generate code documentation.'
    default: './gradlew dokkaHtml'
    required: false

  code-documentation-dst-folder:
    description: 'The destination folder of the generated code documentation.'
    default: './build/dokka/html'
    required: false

  code-documentation-site-folder:
    description: 'The site folder of the generated code documentation.'
    default: 'documentation/code-doc/'
    required: false

  should-generate-openapi-documentation:
    description: 'True if you want to generate the open api documentation, false otherwise.'
    default: 'false'
    required: false

  openapi-documentation-input-file:
    description: 'The input file with rest api specification in open api standard.'
    default: 'docs/openapi/openapi.yml'
    required: false
    
  openapi-documentation-dst-folder:
    description: 'The destination folder of the generated open api documentation.'
    default: 'documentation/openapi-doc'
    required: false

  should-generate-asyncapi-documentation:
    description: 'True if you want to generate the async api documentation, false otherwise.'
    default: 'false'
    required: false

  asyncapi-documentation-input-file:
    description: 'The input file with async api specification in latest async api standard.'
    default: 'docs/asyncapi/asyncapi.yml'
    required: false

  asyncapi-documentation-dst-folder:
    description: 'The destination folder of the generated async api documentation.'
    default: 'documentation/asyncapi-doc'
    required: false

  github-token:
    description: 'The GitHub token, it will be used to push the documentation on gh-pages branch'
    required: true

runs:
  using: composite
  steps:
  - name: Generate AsyncAPI Documentation
    if: inputs.should-generate-asyncapi-documentation == 'true'
    shell: bash
    run: |
      npm install -g @asyncapi/generator@1.9.17
      ag ${{ inputs.asyncapi-documentation-input-file }} @asyncapi/html-template -o ${{ inputs.asyncapi-documentation-dst-folder }}
  - name: Generate Code Documentation
    shell: bash
    if: inputs.should-generate-code-documentation == 'true'
    run: ${{ inputs.code-documentation-generation-command }}
  - name: Generate Swagger OpenAPI Documentation 
    if: inputs.should-generate-openapi-documentation == 'true'
    uses: Legion2/swagger-ui-action@v1
    with:
      output: ${{ inputs.openapi-documentation-dst-folder }}
      spec-file: ${{ inputs.openapi-documentation-input-file }}
  - name: Deploy code documentation on Github Pages
    if: inputs.should-generate-code-documentation == 'true'
    uses: peaceiris/actions-gh-pages@v4
    with:
      github_token: ${{ inputs.github-token }}
      keep_files: true
      publish_dir: ${{ inputs.code-documentation-dst-folder }}
      destination_dir: ${{ inputs.code-documentation-site-folder }}
      user_name: 'github-actions[bot]'
      user_email: 'github-actions[bot]@users.noreply.github.com'
      commit_message: 'docs: update code documentation'
  - name: Deploy OpenAPI documentation on Github Pages
    if: inputs.should-generate-openapi-documentation == 'true'
    uses: peaceiris/actions-gh-pages@v4
    with:
      github_token: ${{ inputs.github-token }}
      keep_files: true
      publish_dir: ${{ inputs.openapi-documentation-dst-folder }}
      destination_dir: ${{ inputs.openapi-documentation-dst-folder }}
      user_name: 'github-actions[bot]'
      user_email: 'github-actions[bot]@users.noreply.github.com'
      commit_message: 'docs: update openapi documentation'
  - name: Deploy AsyncAPI documentation on Github Pages
    if: inputs.should-generate-asyncapi-documentation == 'true'
    uses: peaceiris/actions-gh-pages@v4
    with:
      github_token: ${{ inputs.github-token }}
      keep_files: true
      publish_dir: ${{ inputs.asyncapi-documentation-dst-folder }}
      destination_dir: ${{ inputs.asyncapi-documentation-dst-folder }}
      user_name: 'github-actions[bot]'
      user_email: 'github-actions[bot]@users.noreply.github.com'
      commit_message: 'docs: update asyncapi documentation'
