name: Release

on:
  push:
    paths-ignore:
        - 'CHANGELOG.md'
        - 'LICENSE'
        - 'README.md'
        - 'renovate.json'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the action
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: ./
        with:
          should-generate-code-documentation: false
          should-generate-asyncapi-documentation: true
          asyncapi-documentation-input-file: 'test/asyncapi.yml'
          asyncapi-documentation-dst-folder: 'documentation/asyncapi-doc'
          should-generate-openapi-documentation: true
          openapi-documentation-input-file: 'test/rest-api-docs.yml'
          openapi-documentation-dst-folder: 'documentation/openapi-doc'
          github-token: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs:
      - test
    permissions:
      contents: write
    concurrency:
        # Allow only one release at a time.
        group: release-${{ github.event.number || github.ref }}
    runs-on: ubuntu-latest
    # Release only where secrets are available.
    if: >-
      !github.event.repository.fork
      && (
        github.event_name != 'pull_request'
        || github.event.pull_request.head.repo.full_name == github.repository
      )
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
          fetch-depth: 0
      - name: Find the version of Node from package.json
        id: node-version
        run: echo "version=$(jq -r .engines.node package.json)" >> $GITHUB_OUTPUT
      - name: Install Node
        uses: actions/setup-node@v4.0.4
        with:
          node-version: ${{ steps.node-version.outputs.version }}
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install
          npx semantic-release
  success:
      runs-on: ubuntu-22.04
      needs:
        - test
        - release
      if: >-
        always() && (
          contains(join(needs.*.result, ','), 'failure')
          || !contains(join(needs.*.result, ','), 'cancelled')
        )
      steps:
        - name: Verify that there were no failures
          run: ${{ !contains(join(needs.*.result, ','), 'failure') }}
